# Site settings
baseurl = "http://uqcomputingsociety.github.io/website/"
languageCode = "en-us"
title = "UQCS"


[params]

    # Add generic site parameters here that can be used across partials
    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    name = "UQ Computing Society"
    full_name = "The University of Queeensland Computing Society"

    description = "The UQ Computing Society provides a fun, social and inclusive environment for those interested in coding and technology."

    # Custom assets e.g. "/css/style.css"
	custom_css = ["/css/uqcs.css", "/css/colors.css"]
	custom_js  = []
    custom_ico = "/img/favicon/favicon.ico"
    custom_fonts = []
